
name: lab cow

on:
  watch:
    types: started
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step Up Build Environment
        run: |
          sudo apt-get update && sudo apt-get upgrade
          sudo apt-get install git build-essential gdb-multiarch qemu-system-misc gcc-riscv64-linux-gnu binutils-riscv64-linux-gnu

      - name: Checkout Private Source Repository
        uses: actions/checkout@v3
        with:
          repository: endless-hu/xv6-labs-2021
          token: ${{ secrets.GH_PAT }}
          ref: cow

      - name: run lab cow test
        run: |
          echo The Makefile hash: $(sha256sum Makefile | cut -d' ' -f1)
          echo The usertests.c hash: $(sha256sum user/usertests.c | cut -d' ' -f1)
          echo The cowtest.c hash: $(sha256sum user/cowtest.c | cut -d' ' -f1)
          for i in {1..10}; do
            make grade
            echo "============ Test Round $i complete ==============="
          done
          echo The test runs on commit:
          git log | head -100
