
name: lab fs

on:
  watch:
    types: started
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step Up Build Environment
        run: |
          sudo apt-get update && sudo apt-get upgrade
          sudo apt-get install git build-essential gdb-multiarch qemu-system-misc gcc-riscv64-linux-gnu binutils-riscv64-linux-gnu

      - name: Checkout Private Source Repository
        uses: actions/checkout@v3
        with:
          repository: endless-hu/xv6-labs-2021
          token: ${{ secrets.GH_PAT }}
          ref: fs

      - name: run lab fs test
        run: |
          make grade
          echo The test runs on commit:
          git log | head -10
